- website/netlify.toml
This changes the redirect to the production devtools app.
> fix: devtools prod redirect

- devtools/src/layer.rs
- devtools/src/visitors.rs
The instrumentation would crash when handling updater spans since they can sometimes have empty fields. This PR fixes that
resolves DR-675
> fix: panic on empty updater spans

- web-client/src/components/tauri/configuration-value/flags.tsx
I missed this when we did the livestream review. The `isInConfig` function was missing parentheses and because of that the value was incorrectly selected.
> fix: set default flag was not being selected correctly

- web-client/src/components/sources/source-pane.tsx
- web-client/src/lib/console/filter-logs.test.ts
- web-client/src/lib/console/fixtures/monitor-data.ts
- web-client/src/lib/tauri/tauri-conf-schema.ts
- web-client/src/views/dashboard/console.tsx
This takes care of the linter warnings we collected.
In most cases using the `<Show>` tag with its accessor function solved the problems. 
For the tests of the console tab I disabled the warnings for now since typing for test fixtures is not as important. 
Fixes DT-70
> Fix lint warnings

- devtools/src/layer.rs
- devtools/src/visitors.rs
- web-client/src/views/dashboard/console.tsx
The `tracing-log` interop layer reports log metadata in a different format, this PR adds handling for these special metadata keys to improve the quality of reported log metadata
> fix: improve reported metadata when target is `log`

- SECURITY.md
This fixes a wrong contact email address in the text of the disclosure section.
> Fix Security Mail Contact Domain

- devtools/src/builder.rs
- devtools/src/error.rs
Attempts to pick another free port if the default (or configured one) is not available.
Also adds a `strict_port` setting that can be used to disable this behaviour.
resolves DT-33
> fix: pick free port

- web-client/src/components/span/span-detail-trace.tsx
- web-client/src/lib/connection/monitor.ts
- web-client/src/lib/formatters.ts
- web-client/src/lib/span/normalize-spans.ts
- web-client/src/lib/span/update-spans.ts
This PR adds two improvements to the span details view that expand the graphical span visualizations with some hard data.
- The full duration of the span
- When clicking a "work block" (idk what to call this) it will display when work started, when it ended, what thread performed the work and how long it took
Clicking a "work block" 👇
Clicking a span 👇
> feat: add span details numbers

- web-client/src/lib/tauri/config/retrieve-configurations.ts
@lucasfernog-crabnebula noticed that configurations were not properly retrieved for tauri v2. This aims to fix the race condition that occured when trying to lookup the tauri version while retrieving the configuration.
> fix: retrieve tauri version from monitor data for retrieve configurations

- web-client/src/components/span/span-list.tsx
Fixes DT-43
This prevents the name column from overflowing into other columns like this:
After:
> fix: calls tab name column bleeding

- clients/web/src/lib/span/normalize-spans.ts
This basically fixes the error getting thrown on spans that don't have an exit yet.
Even though I have to say that the underlying code is really wonky in the first place (I added the question mark to "restore the original behavior":
The original line looked like this:
```typescript
const width = scaleToMax([span.exits[i] - enter], allExits - allEnters)[0];
```
If we the span.exits array is empty it will pretty much resolve to something like:
```typescript
undefined - number = NaN
```
And then it will
```typescript
scaleToMax(NaN, number);
// -> 
(NaN / number) * 100 = NaN
```
Which looks hella ugly and should be revised in the future but does not throw an error.
The updated code:
```typescript
const exited = span.exits[i]?.timestamp;
const width = scaleToMax(
[exited - entered.timestamp], …
```
> fix: property access on undefined exit span

- clients/web/package.json
- clients/web/pnpm-lock.yaml
`vite-plugin-static-copy` 1.0.0 drops support for Vite 4.
> revert vite-plugin-static-copy

- clients/web/netlify.toml
This adds a redirect rule for the old `/app` links to redirect to the main site, hopefully this works 🤞
> Add redirect rule for /app

- clients/web/src/lib/connection/transport.tsx
This is just a two-line change that forwards the number of spans/events the rust instrumentation had to drop bc it was running out of buffer space. This is helpful for us to tweak the internal settings and important for end users since dropped events equal data loss and that is a bad experience all around.
> feat: report the number of dropped events to sentry

- clients/web/csp.js
- clients/web/netlify.toml
- clients/web/package.json
- clients/web/pnpm-lock.yaml
- clients/web/vite.config.ts
> Add CSP to DevTools app

- clients/web/csp.js
This allow any PORT in localhost since the web-client has no control over at which port the gRPC will be serving from.
> Fix: CSP is blocking our gRPC connection

- DEVELOPING.md
This renames `ARCHITECTURE.md ` to  `DEVELOPING.md` and expands the document with a few generally helpful infos
> Update and rename ARCHITECTURE.md to DEVELOPING.md

- clients/web/.husky/pre-commit
- clients/web/package.json
- clients/web/pnpm-lock.yaml
> [!NOTE]
> Changes only apply to `clients/web`
This enables us to run:
```sh
pnpm format
```
and 
```sh
pnpm lint
```
for staged git files. 
Fixes DT-72
> Add Husky to enable linting and formatting as pre-commit hooks

- .github/workflows/spelling.yml
To reduce security risks and to improve stability, the spell check action should not point to a moving target (master branch).
I pinned this to the [v1.19.0](https://github.com/crate-ci/typos/tree/v1.19.0) release tag and we need to manually update in case of future releases.
> Pin Spellcheck Action Version

- clients/web/src/components/auto-scroll-pane.tsx
There seems to be the possibility of the virtualizer not reacting fast enough to a change to the underlying datastream. For example when filtering and thus voiding the datastream it might still want to access a previous index. 
This simple change should prevent the error from occuring.
Fixed DT-119
> Hotfix: console throwing error when filtering while a lot of new logs are coming in

- clients/web/netlify.toml
Just noticed with @tillmann-crabnebula that our redirect rules are eating the redirect for the sentry tunnel. So sentry reporting is not working at the moment :(
This PR should fix that. Fixes DT-122
> fix: sentry tunnel redirect

- clients/web/netlify.toml
This fixes our headers definition in the netlify.toml. Could confirm it on the branch deploy:
Fixes DT-123
> fix: header toml

- clients/web/src/components/calls/detail-pane/traces/popover/content.tsx
For internal reference from sentry:
https://crabnebula-ltd.sentry.io/issues/5314877209/?alert_rule_id=14825039&alert_timestamp=1715073935816&alert_type=email&environment=production&notification_uuid=87884c0c-8292-467c-a95a-ad3d7e09a86c&project=4506303812272128&referrer=alert_email
```
TypeError
Cannot read properties of undefined (reading 'timestamp')
```
`../../src/components/calls/detail-pane/traces/popover/content.tsx in reduce at line 13:26`
When a trace is still running it is possible that it has enters without an exit. This case was not handled in the popover content. This PR makes sure that the exit we are trying to access exists.
> Hotfix: Accessing undefined exits in traces

- clients/web/public/icons/copy.svg
- clients/web/src/components/console/log-event/field.tsx
- clients/web/src/lib/formatters.ts
Shorten the file path to one directory before the src (if possible) and make all entries word-breakable by inserting zero-width spaces.
> feat: shorten log file paths

- clients/web/src/lib/span/format-span.ts
- clients/web/src/lib/span/update/kinds/detectKind.ts
- clients/web/src/lib/span/update/kinds/ipc/detect-ipc-kind.ts
- clients/web/src/lib/span/update/kinds/ipc/detect-ipc-trace.ts
- clients/web/src/lib/span/update/kinds/ipc/ipc-spans.ts
I noticed that when the `app:setup` root span is still in the buffer. The IPC commands would not get rendered in the calls list.
To prevent this we need to softly/shallowly detect their kind when they get created. 
This PR aims to solve this issue.
Behaviour before:
IPC commands not showing up in calls list when `app:setup` was received from instrumentation
Behaviour after:
IPC commands are still shown but as second level spans
> fix: this readds soft detection (kind only) for spans

- clients/web/package.json
- clients/web/pnpm-lock.yaml
- clients/web/src/lib/load-fathom.ts
- clients/web/src/render-client.tsx
- clients/web/tsconfig.json
This PR adds support to add the privacy friendly [fathom](https://usefathom.com/) tracking pixel.
`VITE_FATHOM_URL` and `VITE_FATHOM_ID`
Closes DT-115
> Feat: add support for fathom tracking pixel

- .github/workflows/ci-v1.yml
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/devtools-v1/Cargo.lock
- crates/devtools-v1/Cargo.toml
- examples/tauri-v1/Cargo.lock
Bumps the MSRV since `cargo-platform` (dependency of `tauri-utils`) bumped theirs to 1.73
> fix: bump MSRV from 1.70 to 1.73

- clients/web/src/components/dialogs/safari-not-supported-dialog.tsx
- clients/web/src/views/connect.tsx
This PR adds a modal that will be displayed to all safari users notifying them that DevTools Web currently does not support safari:
Closes DT-51
> feat: add safari not support modal

- clients/web/src/components/virtual-list.tsx
Solid seems to optimize the if statement in the `createEffect` call, in this case it breaks reactivity for me :/
I rewrote the code to work around this.
> fix: autoscroll reactivity

- clients/web/src/components/sources/source-pane.tsx
- clients/web/src/lib/code-highlight.ts
- clients/web/src/lib/sources/file-entries.ts
This adds proper handling for `.jsx` and `.tsx` file types in our sources panel.
It also adds a graceful fallback to text display if for some reason the language could not be found.
Closes DT-155
> feat: add shiki support for `.tsx` and `.jsx` and add graceful fallback (text display)

- clients/web/src/lib/load-fathom.ts
TLDR:
Tracking of SPA navigations might have been not working. Tracking of initial page load was not affected.
When working on integrating Fathom for cloud @beanow-at-crabnebula mentioned that the tracking might be off when using the SPA navigation. After looking at the Fathom docs. It seems like it is best to add the `data-spa` attribute for good measure:
https://usefathom.com/docs/script/script-advanced#spa
> fix: add the `data-spa` attribute to the fathom script

- crates/devtools/README.md
Relative URLs are broken on https://crates.io/crates/devtools. This replaces the URL with a full one.
> chore: points to full URL in img

- clients/web/csp.js
- clients/web/index.html
- clients/web/package.json
- clients/web/pnpm-lock.yaml
- clients/web/src/components/calls/detail-pane/traces/popover/tool-tip/row.tsx
Addresses #366; we are not getting around inline styles, as both `@tanstack/solid-virtual` (all virtualized scrolling lists) and `@kobalte/core`(tooltips) require them; includes CSP settings to allow for fathom. Some of the other settings seem to have been previously fixed, but never deployed.
> fix: csp settings

- .github/workflows/ci-v1.yml
- .github/workflows/release-plz.yml
The live rollout fails because the github workflow still targets an older version of ubuntu, so the required package libwebkit2gtk-4.0-dev is no longer available, since it got updated to libwebkit2gtk-4.1-dev.
> fix: update dependency versions for ubuntu-latest
